# Makefile for directory physics/hzdiffu

DEVTOP = ../..
include ../../configure.user

lib:
	(cd simple; $(MAKE) all);

code:
	(cd simple; $(MAKE) code);

little_f:
	(cd simple; $(MAKE) little_f);
clean:
	(cd simple; $(MAKE) clean);
