# Makefile for directory dynamics

DEVTOP = ..
include ../configure.user

lib:
	(cd nonhydro; $(MAKE) all)

code:
	(cd nonhydro; $(MAKE) code)

little_f:
	(cd nonhydro; $(MAKE) little_f)

clean:
	(cd nonhydro; $(MAKE) clean)
